# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def gradedRectangle(x0=None,y0=None,lx=None,ly=None,Nx=None,Ny=None,*args,**kwargs):
    varargin = gradedRectangle.varargin
    nargin = gradedRectangle.nargin

    ##
#==============================================================================
# Copyright (c) 2016 Universit de Lorraine & Lule tekniska universitet
# Author: Luca Di Stasio <luca.distasio@gmail.com>
#                        <luca.distasio@ingpec.eu>
    
    # Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 
# Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
# Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in
# the documentation and/or other materials provided with the distribution
# Neither the name of the Universit de Lorraine or Lule tekniska universitet
# nor the names of its contributors may be used to endorse or promote products
# derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#==============================================================================
    
    #  DESCRIPTION
#  
#  A function to create a regular mesh of quadrilaterals in a rectangular
#  geometry with n zones with different element size
    
    #  Input: x0 - scalar - x-coordinate of center
#         y0 - scalar - y-coordinate of center
#         lx - [M x 1] vector - Side length in each one of the M mesh regions in x-direction
#         ly - [N x 1] vector - Side length in each one of the N mesh regions in y-direction
#         Nx - [M x 1] vector - Number of ELEMENTS in each one of the M mesh regions in x-direction
#         Ny - [N x 1] vector - Number of ELEMENTS in each one of the N mesh regions in y-direction
    
    #  Output: mesh - (sum(Nx)+1)*(sum(Ny)+1) x 2 matrix - mesh nodes ordered through helical
#          indexing
    
    ##
    
    M=size(Nx,1)
    N=size(Ny,1)
    deltax=lx / Nx
    deltay=ly / Ny
    nodesx=zeros(M + 1,1)
    nodesy=zeros(N + 1,1)
    nodesx[1]=x0 - dot(0.5,sum(lx))
    nodesy[1]=y0 - dot(0.5,sum(ly))
    for m in arange(2,M + 1).reshape(-1):
        nodesx[m]=nodesx[m - 1] + lx[m - 1]
    
    for n in arange(2,N + 1).reshape(-1):
        nodesy[n]=nodesy[n - 1] + ly[n - 1]
    
    xs=matlabarray([])
    ys=matlabarray([])
    for m in arange(1,M).reshape(-1):
        addVec=(arange(nodesx[m],nodesx[m + 1],deltax[m])).T
        xs=matlabarray(cat([xs],[addVec[1:end() - 1]]))
    
    xs=matlabarray(cat([xs],[x0 + dot(0.5,sum(lx))]))
    for n in arange(1,N).reshape(-1):
        addVec=(arange(nodesy[n],nodesy[n + 1],deltay[n])).T
        ys=matlabarray(cat([ys],[addVec[1:end() - 1]]))
    
    ys=matlabarray(cat([ys],[y0 + dot(0.5,sum(ly))]))
    mesh=zeros(dot((sum(Nx) + 1),(sum(Ny) + 1)),2)
    for j in arange(1,(sum(Ny) + 1)).reshape(-1):
        mesh[dot((j - 1),(sum(Nx) + 1)) + 1:dot(j,(sum(Nx) + 1)),1]=xs
        mesh[dot((j - 1),(sum(Nx) + 1)) + 1:dot(j,(sum(Nx) + 1)),2]=dot(ys[j],ones((sum(Nx) + 1),1))
    
    return mesh