# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def get_boundaryelementsets(*args,**kwargs):
    varargin = get_boundaryelementsets.varargin
    nargin = get_boundaryelementsets.nargin
