# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def getedge_fromnodes2D(p1=None,p2=None,edges=None,*args,**kwargs):
    varargin = getedge_fromnodes2D.varargin
    nargin = getedge_fromnodes2D.nargin

    ##
#        Project: Fluid-Structure Interaction on Deformable Surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: April 24th, 2014
#    Last update: April 24th, 2014
    
    #          Input: 1 x 3 vector of point in plane (indices + coordinates)
#                 1 x 3 vector of point in plane (indices + coordinates)
#         Output: edge id
    
    edge=0
    i=1
    search=1
    while search and i <= size(edges,1):

        if (p1[1,1] == edges[i,2] and p2[1,1] == edges[i,3]) or (p1[1,1] == edges[i,3] and p2[1,1] == edges[i,2]):
            edge=edges[i,1]
            search=0
        i=i + 1

    
    return edge