# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def analytictransformation(D=None,lattice=None,fhandle=None,*args,**kwargs):
    varargin = analytictransformation.varargin
    nargin = analytictransformation.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: March 27th, 2014
#    Last update: August 6th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    if 2 == D:
        lattice[:,3:4]=fhandle[lattice[:,3],lattice[:,4]]
        lattice[:,5:6]=lattice[:,3:4]
    else:
        if 3 == D:
            lattice[:,4:6]=fhandle[lattice[:,4],lattice[:,5],lattice[:,6]]
            lattice[:,7:9]=lattice[:,4:6]
        else:
            disp('Dimension of space requested is currently not supported')
    
    return lattice