# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def cylindricalcoordinates(r=None,theta=None,z=None,*args,**kwargs):
    varargin = cylindricalcoordinates.varargin
    nargin = cylindricalcoordinates.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: August 6th, 2014
#    Last update: August 6th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    coords=matlabarray(cat(multiply(r,cos(theta)),multiply(r,sin(theta)),z))
    return coords